### ISSUE TITLE
publish samples of preprocessed files for spoken articles

### ISSUE THREAD

**Issue by timobaumann** [hainoon/wikipediareader#4]
Make available manually corrected(?) versions of spoken articles from the paper

**Comment by KujaEx** [comment]
Thanks for fixing the maven pom file. Like you said now there is an exception when you start "StartUp.java":
```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$99(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at model.SynthesizeModel.run(SynthesizeModel.java:105)
	at model.Write_Model.erstelleBenoetigteInputDateien(Write_Model.java:1148)
	at model.Write_Model.<init>(Write_Model.java:123)
	at model.Navigation_Impl.<init>(Navigation_Impl.java:35)
	at player.Player_javafx.init(Player_javafx.java:526)
	at player.Player_javafx.<init>(Player_javafx.java:92)
	at controler.Controller.start(Controller.java:104)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$106(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$119(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	... 1 more
```

You said something about preprocessed articles. On the main page you can download for example "SWC_German.tar" (~14.2GB). Is it possible to include them somehow?

**Comment by timobaumann** [comment]
try this link: https://www2.informatik.uni-hamburg.de/nats/pub/SWC/wikipediareader-preprocessed-articles.tar.gz

**Comment by timobaumann** [comment]
actually, leaving open because this must be referenced from the readme
